# Generated by Django 5.0.6 on 2024-06-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_landing', '0002_job_candidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
